# PostgreSQL。バージョン9.3以上がサポートされます。
#
# pgドライバーのインストール：
#   gem install pg
# macOS with Homebrewの場合：
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# Windowsの場合：
#   gem install pg
#       win32ビルドを選択してください。
#       PostgreSQLをインストールし、その/binディレクトリをパスに追加してください。
#
# Gemfileを使用して設定
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # 接続プーリングの詳細については、Rails設定ガイドを参照してください
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railstest_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: railstest_test
  username: postgres
  password: password
  host: db
  port: 5432

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
